In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [33]:
df = pd.read_csv('/Users/srisuphachawla/Downloads/stock_market_data.csv', header = [0,1])
df

           Price       Close                                High              \
          Ticker        AAPL        MSFT        TSLA        AAPL        MSFT
0           Date         NaN         NaN         NaN         NaN         NaN
1     2018-01-02   40.341885   79.050354   21.368668   40.351254   79.381456
2     2018-01-03   40.334866   79.418282   21.150000   40.878192   79.565441
3     2018-01-04   40.522221   80.117271   20.974667   40.625266   80.623123
4     2018-01-05   40.983578   81.110565   21.105333   41.070228   81.312906
...          ...         ...         ...         ...         ...         ...
2032  2026-02-02  270.010010  423.369995  421.809998  270.489990  430.739990
2033  2026-02-03  269.480011  411.209991  421.959991  271.880005  422.049988
2034  2026-02-04  276.489990  414.190002  406.010010  278.950012  419.799988
2035  2026-02-05  275.910004  393.670013  397.209991  279.500000  408.299988
2036  2026-02-06  278.119995  401.140015  411.109985  280.910004  401.790009

                         Low                                Open              \
            TSLA        AAPL        MSFT        TSLA        AAPL        MSFT
0            NaN         NaN         NaN         NaN         NaN         NaN
1      21.474001   39.639309   78.636481   20.733334   39.850084   79.215905
2      21.683332   40.271636   79.068788   21.036667   40.405124   79.151560
3      21.236668   40.299739   79.620619   20.378668   40.407465   79.639010
4      21.149332   40.526904   80.411572   20.799999   40.618239   80.623112
...          ...         ...         ...         ...         ...         ...
2032  427.149994  259.209991  422.250000  414.500000  260.029999  430.239990
2033  428.559998  267.609985  408.559998  413.690002  269.200012  422.010010
2034  423.899994  272.290009  409.239990  399.179993  272.290009  411.000000
2035  402.100006  273.230011  392.320007  387.529999  278.130005  407.440002
2036  414.549988  276.929993  392.920013  397.750000  277.119995  399.170013

                       Volume
            TSLA         AAPL        MSFT         TSLA
0            NaN          NaN         NaN          NaN
1      20.799999  102223600.0  22483800.0   65283000.0
2      21.400000  118071600.0  26061400.0   67822500.0
3      20.858000   89738400.0  21912000.0  149194500.0
4      21.108000   94640000.0  23407100.0   68868000.0
...          ...          ...         ...          ...
2032  421.290009   73913400.0  42219900.0   58739500.0
2033  424.269989   64394700.0  61424100.0   56886500.0
2034  420.459991   90545700.0  45012400.0   74606900.0
2035  397.019989   52977400.0  66289200.0   72819800.0
2036  400.869995   50420700.0  53403600.0   62559600.0

[2037 rows x 16 columns]

# Pre-processesing to consider:
1. Ticker as column name
2. clean up the dates
3. remove the row Date since Nan

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2037 entries, 0 to 2036
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (Price, Ticker)  2037 non-null   object
 1   (Close, AAPL)    2036 non-null   float64
 2   (Close, MSFT)    2036 non-null   float64
 3   (Close, TSLA)    2036 non-null   float64
 4   (High, AAPL)     2036 non-null   float64
 5   (High, MSFT)     2036 non-null   float64
 6   (High, TSLA)     2036 non-null   float64
 7   (Low, AAPL)      2036 non-null   float64
 8   (Low, MSFT)      2036 non-null   float64
 9   (Low, TSLA)      2036 non-null   float64
 10  (Open, AAPL)     2036 non-null   float64
 11  (Open, MSFT)     2036 non-null   float64
 12  (Open, TSLA)     2036 non-null   float64
 13  (Volume, AAPL)   2036 non-null   float64
 14  (Volume, MSFT)   2036 non-null   float64
 15  (Volume, TSLA)   2036 non-null   float64
dtypes: float64(15), object(1)
memory usage: 254.8+ KB

In [37]:
# removing the faux date row
df = df.iloc[1:].copy()

In [57]:
# renaming our Ticker column into Date 
df = df.rename(columns={('Price','Ticker'): 'Date'})
df

           Price       Close                                High              \
            Date        AAPL        MSFT        TSLA        AAPL        MSFT
1     2018-01-02   40.341885   79.050354   21.368668   40.351254   79.381456
2     2018-01-03   40.334866   79.418282   21.150000   40.878192   79.565441
3     2018-01-04   40.522221   80.117271   20.974667   40.625266   80.623123
4     2018-01-05   40.983578   81.110565   21.105333   41.070228   81.312906
5     2018-01-08   40.831341   81.193336   22.427334   41.126421   81.469257
...          ...         ...         ...         ...         ...         ...
2032  2026-02-02  270.010010  423.369995  421.809998  270.489990  430.739990
2033  2026-02-03  269.480011  411.209991  421.959991  271.880005  422.049988
2034  2026-02-04  276.489990  414.190002  406.010010  278.950012  419.799988
2035  2026-02-05  275.910004  393.670013  397.209991  279.500000  408.299988
2036  2026-02-06  278.119995  401.140015  411.109985  280.910004  401.790009

                         Low                                Open              \
            TSLA        AAPL        MSFT        TSLA        AAPL        MSFT
1      21.474001   39.639309   78.636481   20.733334   39.850084   79.215905
2      21.683332   40.271636   79.068788   21.036667   40.405124   79.151560
3      21.236668   40.299739   79.620619   20.378668   40.407465   79.639010
4      21.149332   40.526904   80.411572   20.799999   40.618239   80.623112
5      22.468000   40.732977   80.567923   21.033333   40.831341   81.119757
...          ...         ...         ...         ...         ...         ...
2032  427.149994  259.209991  422.250000  414.500000  260.029999  430.239990
2033  428.559998  267.609985  408.559998  413.690002  269.200012  422.010010
2034  423.899994  272.290009  409.239990  399.179993  272.290009  411.000000
2035  402.100006  273.230011  392.320007  387.529999  278.130005  407.440002
2036  414.549988  276.929993  392.920013  397.750000  277.119995  399.170013

                       Volume
            TSLA         AAPL        MSFT         TSLA
1      20.799999  102223600.0  22483800.0   65283000.0
2      21.400000  118071600.0  26061400.0   67822500.0
3      20.858000   89738400.0  21912000.0  149194500.0
4      21.108000   94640000.0  23407100.0   68868000.0
5      21.066668   82271200.0  22113000.0  147891000.0
...          ...          ...         ...          ...
2032  421.290009   73913400.0  42219900.0   58739500.0
2033  424.269989   64394700.0  61424100.0   56886500.0
2034  420.459991   90545700.0  45012400.0   74606900.0
2035  397.019989   52977400.0  66289200.0   72819800.0
2036  400.869995   50420700.0  53403600.0   62559600.0

[2036 rows x 16 columns]

In [66]:
df.columns

MultiIndex([( 'Price', 'Date'),
            ( 'Close', 'AAPL'),
            ( 'Close', 'MSFT'),
            ( 'Close', 'TSLA'),
            (  'High', 'AAPL'),
            (  'High', 'MSFT'),
            (  'High', 'TSLA'),
            (   'Low', 'AAPL'),
            (   'Low', 'MSFT'),
            (   'Low', 'TSLA'),
            (  'Open', 'AAPL'),
            (  'Open', 'MSFT'),
            (  'Open', 'TSLA'),
            ('Volume', 'AAPL'),
            ('Volume', 'MSFT'),
            ('Volume', 'TSLA')],
           )